name: BBInaseem
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

# IOS version
version: 1.0.6+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  rounded_loading_button_plus: ^3.0.1
  line_icons: ^2.0.3
  intl: ^0.19.0
  flutter_native_splash: any
  auto_size_text_pk: ^3.0.0
  #flutter_filter_dialog: ^1.0.4
  flutter_image_compress: ^2.0.3
  url_launcher: ^6.1.12
  whatsapp_unilink: ^2.1.0
  cached_network_image: ^3.2.3
  community_material_icon: ^5.9.55
  card_swiper: ^3.0.1
  http: ^1.1.0
  crypto: ^3.0.3
  device_info_plus: ^11.5.0
  modal_bottom_sheet: ^3.0.0-pre
  photo_view: ^0.15.0
  #flutter_cached_pdfview: ^0.4.1
  syncfusion_flutter_pdfviewer: ^30.2.6
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1+2
  logger: ^2.4.0
  iconsax: ^0.0.8
  lottie: ^3.1.2
  dio: ^5.2.1+1
  timeline_tile: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  auto_animated: ^3.2.0
  socket_io_client: ^2.0.1
  google_maps_flutter: ^2.3.1
  geolocator: ^12.0.0
  location: ^7.0.0
  empty_widget_pro: ^0.0.5
  file_picker: ^8.0.6
  #flutter_pdfview: ^1.3.0
  #parse_server_sdk_flutter: ^3.1.0
  #chat_bubbles: ^1.2.0
  just_audio: ^0.9.34
  audio_video_progress_bar: ^2.0.3
  just_waveform: ^0.0.5
  image_picker: ^1.0.4
  record: ^6.1.1
  flutter_audio_waveforms: ^1.2.1+8
  flutter_svg: ^2.0.7
  uuid: ^4.4.2
  z_time_ago: ^0.1.2
  #database
  #sembast: ^3.4.3+1
  visibility_detector: ^0.4.0+2
  qr_code_scanner: ^1.0.1
  audio_session: ^0.1.16
  package_info_plus: ^8.0.1
  flutter_app_badger: ^1.5.0
  another_flushbar: ^1.12.30
  gradient_borders: ^1.0.0
  flutter_arc_speed_dial: ^2.0.1
  loader_overlay: ^4.0.1
  flutter_awesome_select_clone: ^7.5.0
  image_gallery_saver_plus: ^4.0.1
  dots_indicator: ^3.0.0
  flutter_device_id: ^1.0.1

  another_audio_recorder: ^1.0.1
  flutter_pdfview: ^1.4.3

  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  mime: ^1.0.4
  flutter_linkify: ^6.0.0
  file_saver: ^0.2.12

  upgrader: ^11.5.0
  restart_app: ^1.2.1
  open_file: ^3.5.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

flutter:
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/almarai_bold.ttf
          weight: 700
        - asset: assets/fonts/almarai_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/almarai_light.ttf
          weight: 300
        - asset: assets/fonts/almarai_regular.ttf
          style: normal
          weight: 400
  uses-material-design: true

  assets:
    - assets/img/
    - assets/fonts/
    - assets/lang/
    - assets/img/dashboard/
    - assets/lottie/

flutter_native_splash:
  ios: true
  color: "#ffffff"
  image: "assets/img/logo.png"

  android_12:
    image: "assets/img/logo.png"
    color: "#ffffff"
#  android_13:
#    image: "assets/img/ايكونه تطبيق2.png"
#    color: "#ffffff"
